#!/bin/csh -f

# User params to chane input/output behaviour
set refresh_spectra = 0
set make_plot = 0

# Don't change these or you'll change the actual results.
set del = 7200
set rr = 10
set nr = 0
set tc = 1000
#set tc = 1500
set fstt = 40
set fst = 50
set fsp = 120
set tst = 22
set tsp = 23
set sm = 8
set results_dir = H2Case
set calobs=/data5/edges/data/CalibrationObservations/Receiver01/Receiver01_25C_2015_09_02_040_to_200MHz/Spectra

# Make the directory where we'll output the final results of this script.
mkdir -p $results_dir

# Read the (concatenated) ACQ files and write them to txt
if (($refresh_spectra == 1) || !( -f $results_dir/spe_loadr.txt) ) then
echo "Reading Ambient Files... check log at ambient-read.log"
cat $calobs/Ambient_01_2015_245_02_00_00_lab.acq >! temp
cat $calobs/Ambient_01_2015_246_02_00_00_lab.acq >>! temp
../bin/acqplot7amoon  temp -smooth $sm  -fstart $fstt -fstop 110 -pfit 27 -rfi $rr -nrfi $nr -tcal $tc  -tstart 0 -tstop $tsp -delaystart $del > ambient-read.log
mv spe.txt  $results_dir/spe_loadr.txt
rm temp
endif


if (($refresh_spectra == 1) || !( -f $results_dir/spe_hotr.txt) ) then
echo "Reading HotLoad Files... chekc log at hotload-read.log"
cat $calobs/HotLoad_01_2015_246_04_00_00_lab.acq >! temp
cat $calobs/HotLoad_01_2015_247_00_00_00_lab.acq >>! temp
../bin/acqplot7amoon temp -smooth $sm -fstart $fstt -fstop 110 -pfit 27 -rfi $rr -nrfi $nr -tcal $tc -tstart 0 -tstop $tsp -delaystart $del > hotload-read.log
mv spe.txt $results_dir/spe_hotr.txt
rm temp
endif

if (($refresh_spectra == 1) || !( -f $results_dir/spe_openr.txt) ) then
echo "Reading Open Cable Files... check log at opencable-read.log"
cat $calobs/LongCableOpen_01_2015_243_14_00_00_lab.acq >! temp
cat $calobs/LongCableOpen_01_2015_244_00_00_00_lab.acq >>! temp
cat $calobs/LongCableOpen_01_2015_245_00_00_00_lab.acq >>! temp
../bin/acqplot7amoon  temp -smooth $sm -fstart $fstt -fstop 110 -pfit 27 -rfi $rr -nrfi $nr -tcal $tc -tstart 0 -tstop $tsp -delaystart $del > opencable-read.log
mv spe.txt $results_dir/spe_openr.txt
rm temp
endif

if (($refresh_spectra == 1) || !( -f $results_dir/spe_shortr.txt) ) then
echo "Reading  Shorted Cable files... check log at shortcable-read.log"
cat $calobs/LongCableShorted_01_2015_241_04_00_00_lab.acq >! temp
cat $calobs/LongCableShorted_01_2015_242_00_00_00_lab.acq >>! temp
cat $calobs/LongCableShorted_01_2015_243_00_00_00_lab.acq >>! temp
../bin/acqplot7amoon  temp -smooth $sm -fstart $fstt -fstop 110 -pfit 27 -rfi $rr -nrfi $nr -tcal $tc -tstart 0 -tstop $tsp -delaystart $del > shortcable-read.log
mv spe.txt $results_dir/spe_shortr.txt
rm temp
endif


set b = ../data/s11_calibration_low_band_LNA25degC_2015-09-16-12-30-29_simulator2_long.txt
echo Sum $b

# SM: added "-lna_poly 0"  to force the LNA fit to be a Fourier series, as that is what
#     Alan said he did originally.  
../bin/edges2k -fstart 40 -spant $results_dir/spe_hotr.txt -spcold $results_dir/spe_loadr.txt -sphot $results_dir/spe_hotr.txt -spopen $results_dir/spe_openr.txt -spshort $results_dir/spe_shortr.txt -cals11 $b -cals11_hot $b -mfit 1 -wfstart 50 -wfstop 100 -cfit 6 -tcold 296 -thot 399 -nfit1 27 -nfit2 27 -nfit3 11 -nfit4 27 -wfit 5 -Lh -2 -lmode 2 -tant 296 -smooth 8 -wtmode 0 -delaylna 0e-12 -ldb 0 -delaycorr 00e-12 -lna_poly 0

set datestr=`date +"%Y-%m-%d_%H-%M"`
cp specal.txt $results_dir/specal_${datestr}.txt
mv specal.txt $results_dir/specal.txt

# Makes Plots
if ($make_plot==1) then
gs -sDEVICE=ps2write -dNOPAUSE -dBATCH -dSAFER -sOutputFile=spe.ps spehot.pos speamb.pos speopen.pos speshort.pos spevna0.pos spevna1.pos spevna2.pos spevna3.pos spevna4.pos spevna5.pos spewav.pos
psnup -s0.31 -12 -m50 spe.ps comb.ps
ps2pdf comb.ps comb.pdf 
endif
