#!/bin/csh -f
# final case2 lowband1 2016_250 - 2017_095 
set c = S11_blade_low_band_2015_342_03_14.txt.csv

set e = 1
if($e == 1) then
rm spegva*
set day = 616
while ($day <= 830)
rm temp_20

if($day <= 366) set day2 = ` echo $day |awk '{printf("%03d",$1)} '`
if($day <= 366) set year = 2015
if($day > 366 && $day <= 732) set day2 = ` echo $day |awk '{printf("%03d",$1-366)} '`
if($day > 366 && $day <= 732) set year = 2016
if($day > 732) set day2 = ` echo $day |awk '{printf("%03d",$1-732)} '`
if($day > 732) set year = 2017

echo $year\_$day2
if($year == 2016) cat /data4/nmahesh/edges/Low1_field_data/2016/$year\_$day2* >>! temp_20
if($year == 2017) cat /data4/nmahesh/edges/Low1_field_data/2017/$year\_$day2* >>! temp_20

rm spe.txt
/data4/nmahesh/edges/code_from_alan/acqplot7amoon temp_20 -gha 12 -dgha 6 -rfi 2.5 -tcal 1000 -pfit 37 -fstart 40 -fstop 100 -smooth 8 -pkpwrm 40 -peakpwr 3 -minpwr 0.7 -nrfi 4 -dloadmax 1000 -adcov 0.4 -maxrmsf 200 -maxfm 200  >! temp

cp spe.txt spegva$day.txt
@ day = $day + 1
end
endif

set e = 1
if($e == 1) then
rm spesum2.txt
set day = 616
while ($day <= 830)

cp /data4/nmahesh/edges/code_from_alan/newniv.txt azelq.txt # used for H2

cp specal_final_case2.txt specal.txt

rm spe0.txt

/data4/nmahesh/edges/code_from_alan/edges2k  -fstart 50 -fstop 100 -spant spegva$day.txt -s11ant  $c -mfit 3 -wfstart 51 -wfstop 99 -lmode 6 -tant 296 -eorcen 150 -skymode 384 -antaz 354 -wtmode 100 -nfit4 10 -smooth -8 -low 1 -mdd 4 -delayant  0.0e-12 -adb 0.0 -cmb 2 -ldb 0.0 -delaylna 0e-12 -adb 0.0 -delayant 0.0e-12 -test 0 -eoramp -0.5 -eorwid 0 -eorcen 78 -tau 7 


cat spe0.txt >>! spesum2.txt
@ day = $day + 1
end
endif
/data4/nmahesh/edges/code_from_alan/longav spesum2.txt  -lim 0.16 -nfit 5  -dmax 0.5  -fstart 53 -fstop 99 -schk 0 -tchk 200 -rfi 2 -g10  -date -seor -1 -tau 7 -sig 0 -md 1 -out 3

